CREATE TABLE `eyf`.`game_questions` (
  `id` INT NOT NULL,
  `lang` VARCHAR(2) NOT NULL,
  `questionId` INT NOT NULL,
  `answer` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`));
INSERT INTO eyf.game_questions (id, lang, questionId, answer) VALUES
(1, 'ta', 1, 'Pudhu vellai malai'),
(2, 'ta', 2, 'Telephone mani pol siripaval'),
(3, 'ta', 3, 'Kadhal kaditham thetavae'),
(4, 'ta', 4, 'Kadhal rojavae'),
(5, 'ta', 5, 'Enavalae adi Enavalae'),
(6, 'ta', 6, 'Enna vilai alaghae unnai vilaiku'),
(7, 'ta', 7, 'Chinna Chinna Asai'),
(8, 'ta', 8, 'En veetu thotathil poo'),
(9, 'ta', 9, 'Kasumela ada kasuvechu kotukira'),
(10, 'ta', 10, 'Oru mani adithal kannae'),
(11, 'ta', 11, 'Un per solla asai than'),
(12, 'ta', 12, 'Strawberry kannae viveli pennae'),
(13, 'ta', 13, 'Ennai thalata varuvala'),
(14, 'ta', 14, 'O butterfly butterfly en virithai siragai'),
(15, 'ta', 15, 'Colombus colombus vittachu leave'),
(16, 'ta', 16, 'Thuli Thuli Thuli malai'),
(17, 'ta', 17, 'Partha mudhal nalae unnai'),
(18, 'ta', 18, 'Oru ponnu onnu nan pathen'),
(19, 'ta', 19, 'Devathaiya kanden kadhalil vilunthen'),
(20, 'ta', 20, 'Ondra renda asaigal'),
(21, 'ta', 21, 'Manja kattu maina'),
(22, 'ta', 22, 'Pallanguliyin vattan parthen'),
(23, 'ta', 23, 'Google Goolge panni pathen'),
(24, 'ta', 24, 'Minnali pidithu minnali pidithu'),
(25, 'ta', 25, 'Pookal pookum tharunam'),
(26, 'ta', 26, 'Koodamela koodai vechu'),
(27, 'ta', 27, 'Singapennae singapennae'),
(28, 'ta', 28, 'Kadhal cricketu vilunthiduchu wicketu'),
(29, 'ta', 29, 'Lesa Lesa nee ellamal valvathu lessa'),
(30, 'ta', 30, 'Selfie pulla umma umma');